/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class ClienteJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteJFrame.class.getName());
    final String HOST = "localhost";
    final int PUERTO = 5000;
    Socket socket;
    BufferedReader entrada;
    PrintWriter salida;
    private String nombre;
    /**
     * Creates new form ClienteJFrame
     */
    public ClienteJFrame() {
        initComponents();
        iniciarCliente();
    }
    public void iniciarCliente(){
        
        try {
            nombre = JOptionPane.showInputDialog(this, "Ingrese su nombre: ");
            if (nombre == null || nombre.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre.");
                return;
            }
            socket = new Socket(HOST, PUERTO);
            
            entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            salida = new PrintWriter(socket.getOutputStream(), true);
            
            salida.println(nombre);
            txtMensajesRe.append("Conectado al servidor TCP..\n");
            txtMensajesRe.append("Bienvenido(a) "+nombre+"\n");
            txtMensajesRe.append("\n");
            Thread hiloReceptor = new Thread(() -> {
                try {
                    String mensaje;
                    while ((mensaje = entrada.readLine()) != null) {
                        if (mensaje.startsWith("USUARIOS:")) {
                            actualizarUsuarios(mensaje);
                        } else {
                            txtMensajesRe.append(mensaje + "\n");
                        }
                    }
                } catch (Exception e) {
                    txtMensajesRe.append("Conexion finalizada.\n");

                }

            });

            hiloReceptor.start();
        } catch (Exception e) {
            txtMensajesRe.append("Error de conexion: " + e.getMessage() + "\n");
        }
    }
    public void actualizarUsuarios(String mensaje) {
        String usuarios = mensaje.substring(9);
        while (cmbUsuarios.getItemCount() > 1) {
            cmbUsuarios.removeItemAt(1);
        }

        int cantidad = 0;
        if (!usuarios.equals("")) {
            String[] lista = usuarios.split(","); /// .split almacena como una lista una palabra "como estas" en dos "como", "estas" quitando espacios en blanco
            for (String usuario : lista) {
                if (!usuario.equals("")) {
                    cmbUsuarios.addItem(usuario);
                    cantidad++;
                }
            }
        }
        lblCantidadClientes.setText(String.valueOf(cantidad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantidadClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensajesRe = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtMensajesEnvi = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        cmbUsuarios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 33, 51));

        jLabel1.setBackground(new java.awt.Color(26, 33, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALA DE CHAT GENERAL:");
        jLabel1.setOpaque(true);

        lblCantidadClientes.setBackground(new java.awt.Color(39, 53, 66));
        lblCantidadClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantidadClientes.setForeground(new java.awt.Color(80, 220, 160));
        lblCantidadClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidadClientes.setText("0");

        txtMensajesRe.setBackground(new java.awt.Color(26, 33, 51));
        txtMensajesRe.setColumns(20);
        txtMensajesRe.setForeground(new java.awt.Color(255, 255, 255));
        txtMensajesRe.setRows(5);
        jScrollPane1.setViewportView(txtMensajesRe);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensajes:");

        txtMensajesEnvi.setBackground(new java.awt.Color(39, 53, 66));
        txtMensajesEnvi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMensajesEnvi.setForeground(new java.awt.Color(255, 255, 255));
        txtMensajesEnvi.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10));

        btnEnviar.setBackground(new java.awt.Color(59, 125, 216));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_ClienteServidor_img/EnviarMensaje.png"))); // NOI18N
        btnEnviar.setText("ENVIAR MENSAJE [>]");
        btnEnviar.setBorder(null);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        cmbUsuarios.setBackground(new java.awt.Color(59, 125, 216));
        cmbUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios en Linea" }));
        cmbUsuarios.setBorder(null);
        cmbUsuarios.setPreferredSize(new java.awt.Dimension(150, 30));
        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_ClienteServidor_img/happiness.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_ClienteServidor_img/clip.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCantidadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMensajesEnvi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtMensajesEnvi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String mensaje = txtMensajesEnvi.getText();
        if (mensaje.equals("")) {
            JOptionPane.showMessageDialog(this,"Debe escribir un mensaje.");
            return;
        }
        salida.println(mensaje);
        txtMensajesEnvi.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadClientes;
    private javax.swing.JTextField txtMensajesEnvi;
    private javax.swing.JTextArea txtMensajesRe;
    // End of variables declaration//GEN-END:variables
}
