/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.net.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author chris
 */
public class ServidorJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServidorJFrame.class.getName());
    final int PUERTO = 5000;
    private List<ManejoHilosClientes> clientes = new ArrayList<>();
    /**
     * Creates new form ServidorJFrame
     */
    public ServidorJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        iniciarServidor();
    }
    public void iniciarServidor(){
        Thread hiloServidor = new Thread(()->{ //Es una expresión lambda. Representa el método run() de la interfaz Runnable de forma compacta.
            try(ServerSocket server = new ServerSocket(PUERTO)){
                txtClientes.append("Servidor iniciado...\n");
                txtClientes.append("Esperando clientes en puerto: "+PUERTO+"\n");
                
                while (true) {                    
                    Socket cliente = server.accept();
                    ManejoHilosClientes manejo = new ManejoHilosClientes(cliente,this);
                    clientes.add(manejo);
                    manejo.start();
                }

            } catch (Exception e) {
                txtClientes.append("Error en el servidor: "+e.getMessage());
            }
        });
        hiloServidor.start();
    }
    
    public void enviarMenATodos(String mensaje){
        for (ManejoHilosClientes cliente : clientes) {
            cliente.enviarMensaje(mensaje);
        }
    }
    
    public void enviarListaUsuarios() {
        String lista = "USUARIOS:";
        for (ManejoHilosClientes cliente : clientes) {
            lista += cliente.getNombre() + ",";
        }
        enviarMenATodos(lista);
    }
    
    public void mostrarMensajes(String mensaje){
        txtMensajes.append(mensaje+"\n");
    }
    
    public void eliminarCliente(ManejoHilosClientes cliente) {
        clientes.remove(cliente);
    }
    
    public void actualizarClientes() {
        txtClientes.setText("");
        lblCantidadClientes.setText(String.valueOf(clientes.size()));
        if (clientes.isEmpty()) {
            txtClientes.append("No hay clientes conectados.\n");
            txtClientes.append("Esperando nuevos clientes en puerto: " + PUERTO + "...\n");
            return;
        }
        for (ManejoHilosClientes cliente : clientes) {
            txtClientes.append("Nombre: "+ cliente.getNombre() + "\n");
            txtClientes.append("IP: " + cliente.getIp()+ "\n");
            txtClientes.append("-------------------------\n");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlServidorPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClientes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextArea();
        lblCantidadClientes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlServidorPrincipal.setBackground(new java.awt.Color(26, 33, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERVIDOR DE CHAT TCP");
        jLabel1.setIconTextGap(10);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clientes Conectados:");

        jScrollPane1.setBorder(null);

        txtClientes.setEditable(false);
        txtClientes.setBackground(new java.awt.Color(39, 53, 66));
        txtClientes.setColumns(20);
        txtClientes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtClientes.setRows(5);
        txtClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane1.setViewportView(txtClientes);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mensajes:");

        jScrollPane2.setBorder(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(468, 160));

        txtMensajes.setEditable(false);
        txtMensajes.setBackground(new java.awt.Color(39, 53, 66));
        txtMensajes.setColumns(20);
        txtMensajes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMensajes.setForeground(new java.awt.Color(255, 255, 255));
        txtMensajes.setRows(5);
        jScrollPane2.setViewportView(txtMensajes);

        lblCantidadClientes.setBackground(new java.awt.Color(39, 53, 66));
        lblCantidadClientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblCantidadClientes.setForeground(new java.awt.Color(80, 220, 160));
        lblCantidadClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidadClientes.setText("0");
        lblCantidadClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 220, 160), 1, true));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_ClienteServidor_img/ServidorTitulo.png"))); // NOI18N

        javax.swing.GroupLayout pnlServidorPrincipalLayout = new javax.swing.GroupLayout(pnlServidorPrincipal);
        pnlServidorPrincipal.setLayout(pnlServidorPrincipalLayout);
        pnlServidorPrincipalLayout.setHorizontalGroup(
            pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServidorPrincipalLayout.createSequentialGroup()
                                            .addGap(0, 24, Short.MAX_VALUE)
                                            .addComponent(jLabel1)))
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCantidadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlServidorPrincipalLayout.setVerticalGroup(
            pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServidorPrincipalLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServidorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCantidadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServidorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServidorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServidorJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadClientes;
    private javax.swing.JPanel pnlServidorPrincipal;
    private javax.swing.JTextArea txtClientes;
    private javax.swing.JTextArea txtMensajes;
    // End of variables declaration//GEN-END:variables
}
